// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUp-asma9X6NWgiHScGXoUgYC3em4RG9Q',
    appId: '1:552215335383:web:fcb634cf942f4a09f63b92',
    messagingSenderId: '552215335383',
    projectId: 'chat-flutter-e2fd2',
    authDomain: 'chat-flutter-e2fd2.firebaseapp.com',
    storageBucket: 'chat-flutter-e2fd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_3O9gAG2cUM2nI0KZEj52iGcWsCRK9M',
    appId: '1:552215335383:android:3f43843fd5dcb7eff63b92',
    messagingSenderId: '552215335383',
    projectId: 'chat-flutter-e2fd2',
    storageBucket: 'chat-flutter-e2fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xbCYzhF8mmQVYAL4XXYYhbw_McwKbj0',
    appId: '1:552215335383:ios:6f98539e051aeb2df63b92',
    messagingSenderId: '552215335383',
    projectId: 'chat-flutter-e2fd2',
    storageBucket: 'chat-flutter-e2fd2.appspot.com',
    androidClientId: '552215335383-l6jsgc0e6f2kn4cqgbctmv2oqcepvvh7.apps.googleusercontent.com',
    iosClientId: '552215335383-hd29ha3uo7q746q8cnt50vo2ql272kjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_xbCYzhF8mmQVYAL4XXYYhbw_McwKbj0',
    appId: '1:552215335383:ios:6f98539e051aeb2df63b92',
    messagingSenderId: '552215335383',
    projectId: 'chat-flutter-e2fd2',
    storageBucket: 'chat-flutter-e2fd2.appspot.com',
    androidClientId: '552215335383-l6jsgc0e6f2kn4cqgbctmv2oqcepvvh7.apps.googleusercontent.com',
    iosClientId: '552215335383-hd29ha3uo7q746q8cnt50vo2ql272kjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
